sudo: false

language: android
env:
  global:
    - ANDROID_SDKS=android-23,sysimg-23 ANDROID_ABI=armeabi-v7a
  matrix:
    - ANDROID_TARGET=android-23
    - ANDROID_TARGET=android-21
    - ANDROID_TARGET=android-19
    - ANDROID_TARGET=android-18
    - ANDROID_TARGET=android-17
    - ANDROID_TARGET=android-16
    - ANDROID_TARGET=android-15
android:
  components:
    - build-tools-23.0.1
    - build-tools-19.1.0
    - android-23
    - sysimg-23
    - android-14
    - sysimg-14
    - extra-android-support
# Additional components
#    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.*intel.+'

before_install:
  - chmod +x gradlew
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &

#before_script:
#    # Make sure the emulator has started before running tests
#    - ./wait_for_emulator

script:
    - ./gradlew assembleFreeDebug
#    - ./gradlew assembleFreeDebug connectedAndroidTestFreeDebug --info
