name: other checks

# run it manually
on: workflow_dispatch

jobs:
  other_checks:
    # there's no need to run it on forks
    if: github.repository == 'spacecowboy/NotePad'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: perform the checkout
        uses: actions/checkout@v3

      - name: perform the validation
        uses: gradle/wrapper-validation-action@v1

      - name: perform the JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: perform Gradle caching
        uses: gradle/gradle-build-action@v2

      - name: perform the Gradle build
        run: ./gradlew build

      - name: run custom tasks for additional checks
        run: ./gradlew checkLanguages checkFastlane

      - name: lint with gradle
        run: ./gradlew lint

# add something else ?
# anything that may be interesting for github ?
# something related to weblate ?
# TODO as of now, this file is USELESS. maybe add "./gradlew lint" on android_build.yml and delete this file ?